//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkdownNote.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkdownNote.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bold {
            get {
                object obj = ResourceManager.GetObject("bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap from {
            get {
                object obj = ResourceManager.GetObject("from", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap h {
            get {
                object obj = ResourceManager.GetObject("h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap italic {
            get {
                object obj = ResourceManager.GetObject("italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 文件未保存，需要保存吗？ 的本地化字符串。
        /// </summary>
        internal static string MsFileNoSave {
            get {
                return ResourceManager.GetString("MsFileNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请升级到Internet Explorer 8及更高版本，虽然可以继续使用，但可能无法正确显示。 的本地化字符串。
        /// </summary>
        internal static string MsIeLowVer {
            get {
                return ResourceManager.GetString("MsIeLowVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建Markdown笔记 的本地化字符串。
        /// </summary>
        internal static string MsNewFileTitle {
            get {
                return ResourceManager.GetString("MsNewFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分设置需要重启软件后生效。 的本地化字符串。
        /// </summary>
        internal static string MsPrefNeedRest {
            get {
                return ResourceManager.GetString("MsPrefNeedRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已保存 的本地化字符串。
        /// </summary>
        internal static string MsPrefNeedRestTitle {
            get {
                return ResourceManager.GetString("MsPrefNeedRestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检查更新... 的本地化字符串。
        /// </summary>
        internal static string MsUpdChecking {
            get {
                return ResourceManager.GetString("MsUpdChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误，无法检查更新，请反馈错误给开发者。 的本地化字符串。
        /// </summary>
        internal static string MsUpdError {
            get {
                return ResourceManager.GetString("MsUpdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误 的本地化字符串。
        /// </summary>
        internal static string MsUpdErrorTitle {
            get {
                return ResourceManager.GetString("MsUpdErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的更新 的本地化字符串。
        /// </summary>
        internal static string MsUpdFound {
            get {
                return ResourceManager.GetString("MsUpdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更新 的本地化字符串。
        /// </summary>
        internal static string MsUpdNo {
            get {
                return ResourceManager.GetString("MsUpdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string MsUpdVerTxt {
            get {
                return ResourceManager.GetString("MsUpdVerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ol {
            get {
                object obj = ResourceManager.GetObject("ol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap safari {
            get {
                object obj = ResourceManager.GetObject("safari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap split {
            get {
                object obj = ResourceManager.GetObject("split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ul {
            get {
                object obj = ResourceManager.GetObject("ul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
